#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
PROMPT_FILE="${SCRIPT_DIR}/signal-loop-prompt.md"

usage() {
  cat <<'EOF'
Usage: tools/signal-loop.sh [--codex|--claude] [--print-prompt] [--date YYYY-MM-DD] [extra args...]

Starts an interactive Codex CLI or Claude CLI session with the repo's signal-loop prompt.

Options:
  --codex         Force Codex CLI
  --claude        Force Claude CLI
  --date DATE     Override the report date injected into the prompt
  --print-prompt  Print the rendered prompt and exit
  --help          Show this help

Environment:
  SIGNAL_LOOP_CLI   Optional override: codex or claude
  SIGNAL_LOOP_DATE  Optional report date override if --date is not passed
EOF
}

requested_cli="${SIGNAL_LOOP_CLI:-}"
report_date="${SIGNAL_LOOP_DATE:-$(date +%F)}"
print_prompt="false"
extra_args=()

while (($# > 0)); do
  case "$1" in
    --codex)
      requested_cli="codex"
      shift
      ;;
    --claude)
      requested_cli="claude"
      shift
      ;;
    --date)
      if (($# < 2)); then
        echo "error: --date requires YYYY-MM-DD" >&2
        exit 1
      fi
      report_date="$2"
      shift 2
      ;;
    --print-prompt)
      print_prompt="true"
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      extra_args+=("$1")
      shift
      ;;
  esac
done

if [[ ! -f "$PROMPT_FILE" ]]; then
  echo "error: missing prompt file at $PROMPT_FILE" >&2
  exit 1
fi

if [[ -z "$requested_cli" ]]; then
  if command -v claude >/dev/null 2>&1; then
    requested_cli="claude"
  elif command -v codex >/dev/null 2>&1; then
    requested_cli="codex"
  else
    echo "error: neither 'claude' nor 'codex' is installed" >&2
    exit 1
  fi
fi

case "$requested_cli" in
  claude|codex)
    ;;
  *)
    echo "error: unsupported CLI '$requested_cli' (expected 'claude' or 'codex')" >&2
    exit 1
    ;;
esac

prompt="$(
  {
    printf 'Repo root: %s\n' "$REPO_ROOT"
    printf 'Report date: %s\n' "$report_date"
    printf 'Local date generated by wrapper: %s\n\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    cat "$PROMPT_FILE"
  }
)"

if [[ "$print_prompt" == "true" ]]; then
  printf '%s\n' "$prompt"
  exit 0
fi

echo "[signal-loop] repo: ${REPO_ROOT}"
echo "[signal-loop] cli: ${requested_cli}"
echo "[signal-loop] date: ${report_date}"
echo "[signal-loop] prompt: ${PROMPT_FILE}"

if [[ "$requested_cli" == "codex" ]]; then
  exec codex -C "$REPO_ROOT" "${extra_args[@]}" "$prompt"
fi

cd "$REPO_ROOT"
exec claude "${extra_args[@]}" "$prompt"
